export type PpdMedicineItem = {
  id: string;
  genericName: string;
  brands: string[];
  commonForms: string[];
  defaultDose: string;
  defaultFrequency: string;
  defaultDuration: string;
  defaultQuantity: string;
  defaultInstructions: string;
  indication: string;
  therapeuticClass: string;
  productInfo: {
    description: string;
    dosageAdvice: string;
    cautions: string;
  };
};

export type PrescriptionItemDraft = {
  id: string;
  genericName: string;
  brand: string;
  strengthForm: string;
  dose: string;
  frequency: string;
  duration: string;
  quantity: string;
  instructions: string;
  indication: string;
  // Backward compatibility fields
  medicineName?: string;
  dosage?: string;
};

export const COMMON_FREQUENCIES = [
  "once a day",
  "once a day (at bedtime)",
  "once a day (in the morning)",
  "twice a day (every 12 hours)",
  "3 times a day (every 8 hours)",
  "4 times a day (every 6 hours)",
  "every 4 to 6 hours as needed",
  "every 8 hours as needed",
  "as needed for pain/fever",
  "as needed for cough",
  "before meals",
  "after meals",
];

export const COMMON_DURATIONS = [
  "3 days",
  "5 days",
  "7 days",
  "10 days",
  "14 days",
  "21 days",
  "30 days",
  "maintenance (30 days)",
  "as needed",
];

export const COMMON_INSTRUCTIONS = [
  "Take with or without food",
  "Take before bedtime",
  "Take strictly after meals",
  "Take 30 minutes before meals",
  "Take 1 hour before or 2 hours after meals",
  "Complete the full antibiotic course",
  "Take with a full glass of water",
  "Chew thoroughly before swallowing",
  "Dissolve in 200 mL of water and drink",
  "Rinse mouth after inhalation",
  "Shake well before use",
];

export const PPD_MEDICINES: PpdMedicineItem[] = [
  {
    id: "montelukast-levocetirizine",
    genericName: "Montelukast + Levocetirizine",
    brands: [
      "Allerkast",
      "Monteka-L",
      "Montemax-L",
      "Levocet-M",
      "Kastair-FX",
      "RiteMED Montelukast + Levocetirizine",
      "Montair-LC",
      "Co-Montelukast",
    ],
    commonForms: [
      "Film-coated tablet 10 mg/5 mg",
      "Chewable tablet 5 mg/2.5 mg",
      "Syrup 4 mg/2.5 mg per 5 mL",
    ],
    defaultDose: "1 Film-coated tablet",
    defaultFrequency: "once a day",
    defaultDuration: "5 days",
    defaultQuantity: "5",
    defaultInstructions: "Take before bedtime",
    indication: "Allergic rhinitis",
    therapeuticClass: "Antihistamine / Leukotriene Receptor Antagonist",
    productInfo: {
      description: "Dual-action combination for seasonal and perennial allergic rhinitis accompanied by asthma or nasal congestion.",
      dosageAdvice: "Adults & adolescents 15yo+: 1 tablet (10mg/5mg) once daily in the evening.",
      cautions: "May cause mild drowsiness. Avoid alcohol. Monitor neuropsychiatric symptoms.",
    },
  },
  {
    id: "azithromycin",
    genericName: "Azithromycin",
    brands: [
      "Azithro-Natrapharm",
      "Zithromax",
      "Zenith",
      "Azitrom",
      "Zmax",
      "RiteMED Azithromycin",
      "Rozith",
      "Macrozit",
    ],
    commonForms: [
      "Film-coated tablet 500 mg",
      "Capsule 250 mg",
      "Oral Suspension 200 mg/5 mL",
    ],
    defaultDose: "1 Film-coated tablet",
    defaultFrequency: "once a day",
    defaultDuration: "5 days",
    defaultQuantity: "5",
    defaultInstructions: "Take with or without food",
    indication: "Bacterial respiratory tract infection",
    therapeuticClass: "Macrolide Antibiotic",
    productInfo: {
      description: "Broad-spectrum macrolide indicated for upper & lower respiratory infections, sinusitis, tonsillitis, and skin infections.",
      dosageAdvice: "Adults: 500 mg once daily for 3 to 5 days. Must complete prescribed duration.",
      cautions: "Caution in patients with hepatic impairment or cardiac arrhythmia (QT prolongation).",
    },
  },
  {
    id: "dextro-ppa-paracetamol",
    genericName: "Dextromethorphan + Phenylpropanolamine + Paracetamol",
    brands: [
      "Tuseran Forte",
      "Decolgen Forte",
      "Neozep Forte",
      "Bioflu",
      "Symdex-E",
      "RiteMED Cough & Cold",
    ],
    commonForms: [
      "Capsule 15 mg/25 mg/325 mg",
      "Caplet 15 mg/25 mg/500 mg",
      "Syrup 10 mg/12.5 mg/250 mg per 5 mL",
    ],
    defaultDose: "1 Capsule",
    defaultFrequency: "3 times a day",
    defaultDuration: "5 days",
    defaultQuantity: "15",
    defaultInstructions: "Take with or without food",
    indication: "Cough, nasal congestion, headache, and fever",
    therapeuticClass: "Antitussive / Decongestant / Analgesic-Antipyretic",
    productInfo: {
      description: "Multi-symptom relief formula for dry non-productive cough, clogged nose, sinus pressure, body aches, and fever.",
      dosageAdvice: "Adults & children 12yo+: 1 capsule every 6 to 8 hours (3 to 4 times a day).",
      cautions: "Caution in hypertension, hyperthyroidism, glaucoma, and renal/liver disease.",
    },
  },
  {
    id: "amoxicillin-clavulanate",
    genericName: "Amoxicillin + Potassium Clavulanate (Co-Amoxiclav)",
    brands: [
      "Augmentin",
      "Natravox",
      "Co-Amoxiclav RiteMED",
      "Curam",
      "Amoclav",
      "Claventin",
    ],
    commonForms: [
      "Film-coated tablet 625 mg",
      "Film-coated tablet 1 g",
      "Oral Suspension 228.5 mg/5 mL",
      "Oral Suspension 457 mg/5 mL",
    ],
    defaultDose: "1 Tablet",
    defaultFrequency: "twice a day (every 12 hours)",
    defaultDuration: "7 days",
    defaultQuantity: "14",
    defaultInstructions: "Take at the start of a meal to minimize gastrointestinal discomfort. Complete 7 days.",
    indication: "Bacterial infection (Sinusitis / Otitis Media / CAP)",
    therapeuticClass: "Beta-lactamase Inhibitor Antibiotic",
    productInfo: {
      description: "Broad-spectrum antibacterial for penicillinase-producing bacterial infections of the respiratory tract, ENT, and skin.",
      dosageAdvice: "625 mg 1 tablet twice or three times daily, or 1g 1 tablet twice daily for 7 to 10 days.",
      cautions: "Contraindicated in penicillin allergy. Discontinue if rash or severe diarrhea develops.",
    },
  },
  {
    id: "amoxicillin",
    genericName: "Amoxicillin",
    brands: [
      "Himox",
      "Amoxil",
      "RiteMED Amoxicillin",
      "Polymox",
      "Moxilin",
      "Pediamox",
    ],
    commonForms: [
      "Capsule 500 mg",
      "Oral Suspension 250 mg/5 mL",
      "Oral Drops 100 mg/mL",
    ],
    defaultDose: "1 Capsule",
    defaultFrequency: "3 times a day (every 8 hours)",
    defaultDuration: "7 days",
    defaultQuantity: "21",
    defaultInstructions: "Take with or without food. Complete full 7-day course.",
    indication: "Bacterial respiratory or dental infection",
    therapeuticClass: "Aminopenicillin Antibiotic",
    productInfo: {
      description: "First-line aminopenicillin for susceptible gram-positive and gram-negative bacterial infections.",
      dosageAdvice: "500 mg every 8 hours for 7 days. Ensure regular dosing intervals.",
      cautions: "Contraindicated in penicillin hypersensitivity.",
    },
  },
  {
    id: "paracetamol",
    genericName: "Paracetamol",
    brands: [
      "Biogesic",
      "Calpol",
      "Tempra",
      "Panadol",
      "RiteMED Paracetamol",
      "Rexidol Forte",
      "Opigesic",
    ],
    commonForms: [
      "Tablet 500 mg",
      "Tablet 650 mg",
      "Syrup 250 mg/5 mL",
      "Oral Drops 100 mg/mL",
    ],
    defaultDose: "1 Tablet",
    defaultFrequency: "every 4 to 6 hours as needed",
    defaultDuration: "3 days",
    defaultQuantity: "10",
    defaultInstructions: "Take after meals. Maximum 4,000 mg (8 tablets) in 24 hours.",
    indication: "Fever and mild to moderate pain",
    therapeuticClass: "Analgesic / Antipyretic",
    productInfo: {
      description: "Gentle and effective first-line treatment for fever, headache, body aches, and general discomfort.",
      dosageAdvice: "500 mg to 1000 mg every 4 to 6 hours as needed. Do not exceed 4g/day.",
      cautions: "Do not combine with other paracetamol-containing products. Caution in liver disease.",
    },
  },
  {
    id: "ibuprofen",
    genericName: "Ibuprofen",
    brands: [
      "Advil",
      "Medicol Advance",
      "Dolan",
      "RiteMED Ibuprofen",
      "Alaxan FR (+Paracetamol)",
      "Brufen",
    ],
    commonForms: [
      "Liquid gel capsule 200 mg",
      "Liquid gel capsule 400 mg",
      "Suspension 100 mg/5 mL",
      "Suspension 200 mg/5 mL",
    ],
    defaultDose: "1 Capsule",
    defaultFrequency: "3 times a day as needed (every 8 hours)",
    defaultDuration: "3 days",
    defaultQuantity: "9",
    defaultInstructions: "Take strictly after meals with a full glass of water",
    indication: "Inflammation, headache, toothache, and musculoskeletal pain",
    therapeuticClass: "NSAID",
    productInfo: {
      description: "Non-steroidal anti-inflammatory drug providing rapid relief from pain, swelling, and fever.",
      dosageAdvice: "200 mg to 400 mg every 6 to 8 hours after meals. Use lowest effective dose.",
      cautions: "Take with food. Contraindicated in active peptic ulcer, severe renal failure, or NSAID asthma.",
    },
  },
  {
    id: "mefenamic-acid",
    genericName: "Mefenamic Acid",
    brands: [
      "Ponstan",
      "Dolfenal",
      "RiteMED Mefenamic Acid",
      "Gardan",
      "Mefenax",
    ],
    commonForms: [
      "Capsule 250 mg",
      "Capsule 500 mg",
      "Tablet 500 mg",
    ],
    defaultDose: "1 Capsule",
    defaultFrequency: "3 times a day as needed (every 8 hours)",
    defaultDuration: "3 days",
    defaultQuantity: "9",
    defaultInstructions: "Take strictly after meals",
    indication: "Primary dysmenorrhea, dental pain, and acute pain",
    therapeuticClass: "NSAID / Analgesic",
    productInfo: {
      description: "Potent NSAID specifically indicated for primary dysmenorrhea, dental post-extraction pain, and acute traumatic pain.",
      dosageAdvice: "500 mg 3 times daily after meals for a maximum of 5 to 7 days.",
      cautions: "Contraindicated in active peptic ulceration or GI bleeding. Always take with meals.",
    },
  },
  {
    id: "cetirizine",
    genericName: "Cetirizine Hydrochloride",
    brands: [
      "Zyrtec",
      "Alnix",
      "Virlix",
      "RiteMED Cetirizine",
      "Cetrine",
      "Histafree",
    ],
    commonForms: [
      "Film-coated tablet 10 mg",
      "Syrup 5 mg/5 mL",
      "Oral Drops 10 mg/mL",
    ],
    defaultDose: "1 Tablet",
    defaultFrequency: "once a day",
    defaultDuration: "7 days",
    defaultQuantity: "7",
    defaultInstructions: "Take before bedtime (may cause mild drowsiness)",
    indication: "Allergic rhinitis, sneezing, itchy eyes, and urticaria",
    therapeuticClass: "Second-Generation Antihistamine",
    productInfo: {
      description: "Rapid-acting non-sedating/low-sedating H1 receptor antagonist for allergic rhinitis and chronic urticaria.",
      dosageAdvice: "Adults: 10 mg once daily, preferably in the evening.",
      cautions: "Caution when driving or operating machinery. Avoid alcohol.",
    },
  },
  {
    id: "levocetirizine",
    genericName: "Levocetirizine Dihydrochloride",
    brands: [
      "Xyzal",
      "Lezyncet",
      "RiteMED Levocetirizine",
      "Zykast",
      "Levrix",
    ],
    commonForms: [
      "Film-coated tablet 5 mg",
      "Oral Solution 2.5 mg/5 mL",
    ],
    defaultDose: "1 Tablet",
    defaultFrequency: "once a day",
    defaultDuration: "7 days",
    defaultQuantity: "7",
    defaultInstructions: "Take once daily in the evening",
    indication: "Allergic rhinitis, allergic conjunctivitis, and chronic urticaria",
    therapeuticClass: "Third-Generation Antihistamine",
    productInfo: {
      description: "Active enantiomer of cetirizine offering high potency and minimal sedative side-effects.",
      dosageAdvice: "Adults and adolescents: 5 mg once daily in the evening.",
      cautions: "Dose reduction in renal impairment.",
    },
  },
  {
    id: "loratadine",
    genericName: "Loratadine",
    brands: [
      "Claritin",
      "Allerdil",
      "RiteMED Loratadine",
      "Lorit",
      "Claricort (+Betamethasone)",
    ],
    commonForms: [
      "Tablet 10 mg",
      "Syrup 5 mg/5 mL",
    ],
    defaultDose: "1 Tablet",
    defaultFrequency: "once a day",
    defaultDuration: "7 days",
    defaultQuantity: "7",
    defaultInstructions: "Take once daily in the morning",
    indication: "Allergic rhinitis, skin allergies, and itching",
    therapeuticClass: "Non-Sedating Antihistamine",
    productInfo: {
      description: "Long-acting, non-sedating tricyclic antihistamine for daytime symptom relief.",
      dosageAdvice: "Adults & children >30kg: 10 mg once daily.",
      cautions: "Safe for daytime work; caution in severe hepatic impairment.",
    },
  },
  {
    id: "cefuroxime-axetil",
    genericName: "Cefuroxime Axetil",
    brands: [
      "Zinnat",
      "Ceftum",
      "RiteMED Cefuroxime",
      "Zinacef",
      "Altacef",
    ],
    commonForms: [
      "Film-coated tablet 500 mg",
      "Film-coated tablet 250 mg",
      "Oral Suspension 125 mg/5 mL",
      "Oral Suspension 250 mg/5 mL",
    ],
    defaultDose: "1 Tablet",
    defaultFrequency: "twice a day (every 12 hours)",
    defaultDuration: "7 days",
    defaultQuantity: "14",
    defaultInstructions: "Take with meals for optimal absorption. Complete 7 days.",
    indication: "Upper/lower respiratory tract infection, UTI, and skin infection",
    therapeuticClass: "Second-Generation Cephalosporin",
    productInfo: {
      description: "Oral cephalosporin with excellent bactericidal activity against respiratory pathogens.",
      dosageAdvice: "500 mg twice daily with food for 7 to 10 days.",
      cautions: "Take with food for best absorption. Do not crush tablets due to bitter taste.",
    },
  },
  {
    id: "cefalexin",
    genericName: "Cefalexin",
    brands: [
      "Ceporex",
      "Ceff",
      "RiteMED Cefalexin",
      "Felexin",
      "Keflex",
    ],
    commonForms: [
      "Capsule 500 mg",
      "Oral Suspension 250 mg/5 mL",
      "Oral Drops 100 mg/mL",
    ],
    defaultDose: "1 Capsule",
    defaultFrequency: "3 times a day (every 8 hours)",
    defaultDuration: "7 days",
    defaultQuantity: "21",
    defaultInstructions: "Take with or without food. Complete 7-day course.",
    indication: "Skin and soft tissue infections, wound infection, and uncomplicated UTI",
    therapeuticClass: "First-Generation Cephalosporin",
    productInfo: {
      description: "First-generation cephalosporin highly effective for staphylococcal and streptococcal skin/wound infections.",
      dosageAdvice: "500 mg every 8 hours for 7 days.",
      cautions: "Caution in patients with penicillin allergy (low cross-reactivity).",
    },
  },
  {
    id: "ciprofloxacin",
    genericName: "Ciprofloxacin",
    brands: [
      "Ciprobay",
      "Ciprox",
      "RiteMED Ciprofloxacin",
      "Quinovid",
      "Cifran",
    ],
    commonForms: [
      "Film-coated tablet 500 mg",
    ],
    defaultDose: "1 Tablet",
    defaultFrequency: "twice a day (every 12 hours)",
    defaultDuration: "7 days",
    defaultQuantity: "14",
    defaultInstructions: "Drink plenty of water. Avoid taking simultaneously with milk, dairy, or antacids.",
    indication: "Urinary tract infection, bacterial gastroenteritis",
    therapeuticClass: "Fluoroquinolone Antibiotic",
    productInfo: {
      description: "Broad-spectrum fluoroquinolone effective against Gram-negative bacteria causing urinary and gastrointestinal infections.",
      dosageAdvice: "500 mg twice daily for 7 days. Space 2 hours away from antacids/calcium.",
      cautions: "Avoid excessive sun exposure. Discontinue if tendon pain or swelling occurs.",
    },
  },
  {
    id: "clindamycin",
    genericName: "Clindamycin Hydrochloride",
    brands: [
      "Dalacin C",
      "Clinacin",
      "RiteMED Clindamycin",
      "Clindatroy",
    ],
    commonForms: [
      "Capsule 300 mg",
      "Capsule 150 mg",
    ],
    defaultDose: "1 Capsule",
    defaultFrequency: "3 times a day (every 8 hours)",
    defaultDuration: "7 days",
    defaultQuantity: "21",
    defaultInstructions: "Take with a full glass of water and remain upright for 30 minutes",
    indication: "Dental abscess, bone infection, and severe soft tissue infection",
    therapeuticClass: "Lincosamide Antibiotic",
    productInfo: {
      description: "Potent anaerobic and Gram-positive antibiotic of choice for dental infections and penicillin-allergic patients.",
      dosageAdvice: "300 mg every 8 hours for 7 days.",
      cautions: "Take with ample water to prevent esophageal irritation. Stop if severe persistent diarrhea occurs.",
    },
  },
  {
    id: "omeprazole",
    genericName: "Omeprazole",
    brands: [
      "Losec",
      "Omepron",
      "RiteMED Omeprazole",
      "Omepten",
      "Gastracid",
      "Prilosec",
    ],
    commonForms: [
      "Capsule 20 mg",
      "Capsule 40 mg",
    ],
    defaultDose: "1 Capsule",
    defaultFrequency: "once a day",
    defaultDuration: "14 days",
    defaultQuantity: "14",
    defaultInstructions: "Take 30 minutes before breakfast on an empty stomach",
    indication: "GERD, acid reflux, gastritis, and peptic ulcer",
    therapeuticClass: "Proton Pump Inhibitor (PPI)",
    productInfo: {
      description: "Potent gastric acid secretion inhibitor providing sustained acid suppression for reflux and gastritis.",
      dosageAdvice: "20 mg to 40 mg once daily 30 minutes before breakfast for 2 to 4 weeks.",
      cautions: "Swallow whole; do not crush or chew capsule pellets.",
    },
  },
  {
    id: "esomeprazole",
    genericName: "Esomeprazole",
    brands: [
      "Nexium",
      "Nexpro",
      "Esomac",
      "RiteMED Esomeprazole",
    ],
    commonForms: [
      "Film-coated tablet 20 mg",
      "Film-coated tablet 40 mg",
    ],
    defaultDose: "1 Tablet",
    defaultFrequency: "once a day",
    defaultDuration: "14 days",
    defaultQuantity: "14",
    defaultInstructions: "Take 30 minutes to 1 hour before breakfast",
    indication: "Gastroesophageal reflux disease (GERD) and erosive esophagitis",
    therapeuticClass: "Proton Pump Inhibitor (PPI)",
    productInfo: {
      description: "S-isomer of omeprazole offering enhanced bioavailability and superior 24-hour intragastric pH control.",
      dosageAdvice: "40 mg once daily for erosive GERD; 20 mg once daily for maintenance.",
      cautions: "Take on an empty stomach before breakfast.",
    },
  },
  {
    id: "antacid-simethicone",
    genericName: "Aluminum Hydroxide + Magnesium Hydroxide + Simethicone",
    brands: [
      "Kremil-S",
      "Kremil-S Advance",
      "Maalox Plus",
      "Mylanta",
    ],
    commonForms: [
      "Chewable tablet",
      "Oral Suspension",
    ],
    defaultDose: "1 to 2 Chewable tablets",
    defaultFrequency: "3 times a day as needed",
    defaultDuration: "5 days",
    defaultQuantity: "10",
    defaultInstructions: "Chew thoroughly 1 hour after meals and at bedtime",
    indication: "Hyperacidity, heartburn, acid indigestion, and gas pain",
    therapeuticClass: "Antacid / Antiflatulent",
    productInfo: {
      description: "Fast-acting relief that neutralizes stomach acid while simethicone disperses gas bubbles.",
      dosageAdvice: "Chew 1 to 2 tablets 1 hour after meals or whenever heartburn occurs.",
      cautions: "Separate from other oral medications by 2 hours.",
    },
  },
  {
    id: "hyoscine-butylbromide",
    genericName: "Hyoscine-N-Butylbromide",
    brands: [
      "Buscopan",
      "Spascol",
      "RiteMED Hyoscine",
      "Relief-H",
    ],
    commonForms: [
      "Sugar-coated tablet 10 mg",
    ],
    defaultDose: "1 Tablet",
    defaultFrequency: "3 times a day as needed",
    defaultDuration: "3 days",
    defaultQuantity: "6",
    defaultInstructions: "Take for stomach cramps or abdominal pain",
    indication: "Abdominal cramps, gastrointestinal spasm, and irritable bowel",
    therapeuticClass: "Antispasmodic",
    productInfo: {
      description: "Targeted smooth muscle antispasmodic that relieves gastrointestinal and urinary tract spasms.",
      dosageAdvice: "10 mg to 20 mg 3 to 4 times daily as needed for cramping.",
      cautions: "Contraindicated in glaucoma, myasthenia gravis, or mechanical bowel obstruction.",
    },
  },
  {
    id: "hyoscine-paracetamol",
    genericName: "Hyoscine-N-Butylbromide + Paracetamol",
    brands: [
      "Buscopan Venus",
      "Buscopan Plus",
    ],
    commonForms: [
      "Film-coated tablet 10 mg/500 mg",
    ],
    defaultDose: "1 Tablet",
    defaultFrequency: "3 times a day as needed",
    defaultDuration: "3 days",
    defaultQuantity: "6",
    defaultInstructions: "Take for severe spasmodic menstrual or abdominal pain",
    indication: "Moderate to severe spasmodic pain and menstrual cramps",
    therapeuticClass: "Antispasmodic / Analgesic",
    productInfo: {
      description: "Dual antispasmodic and analgesic action for painful abdominal and gynecological cramps.",
      dosageAdvice: "1 tablet up to 3 times daily. Maximum 4 tablets in 24 hours.",
      cautions: "Do not exceed recommended dose; avoid duplicate paracetamol.",
    },
  },
  {
    id: "domperidone",
    genericName: "Domperidone",
    brands: [
      "Motilium",
      "Domper",
      "RiteMED Domperidone",
      "Vomidon",
    ],
    commonForms: [
      "Film-coated tablet 10 mg",
      "Oral Suspension 5 mg/5 mL",
    ],
    defaultDose: "1 Tablet",
    defaultFrequency: "3 times a day",
    defaultDuration: "5 days",
    defaultQuantity: "15",
    defaultInstructions: "Take 15 to 30 minutes before meals",
    indication: "Nausea, vomiting, delayed gastric emptying, and bloating",
    therapeuticClass: "Dopamine Antagonist / Prokinetic",
    productInfo: {
      description: "Peripheral dopamine antagonist that stimulates upper gastrointestinal motility and suppresses nausea.",
      dosageAdvice: "10 mg up to 3 times daily before meals. Limit to shortest effective duration.",
      cautions: "Caution in patients with cardiac conduction disorders or QT prolongation.",
    },
  },
  {
    id: "ors",
    genericName: "Oral Rehydration Salts (ORS)",
    brands: [
      "Hydrite",
      "Pedialyte",
      "Glucolyte",
      "RiteMED ORS",
    ],
    commonForms: [
      "Powder sachet for 200 mL solution",
      "Ready-to-drink solution 500 mL",
    ],
    defaultDose: "1 sachet dissolved in 200 mL clean drinking water",
    defaultFrequency: "after each loose bowel movement",
    defaultDuration: "3 days",
    defaultQuantity: "6",
    defaultInstructions: "Sip slowly after each loose stool. Discard unused reconstituted solution after 24 hours.",
    indication: "Dehydration from acute gastroenteritis / diarrhea",
    therapeuticClass: "Oral Electrolyte Replacement",
    productInfo: {
      description: "WHO-formulated oral rehydration salts that restore fluids and electrolytes lost in diarrhea and vomiting.",
      dosageAdvice: "Dissolve 1 sachet in exactly 200 mL drinking water. Drink 200 to 400 mL after each watery stool.",
      cautions: "Mix only with clean drinking water; do not mix with juice or soft drinks.",
    },
  },
  {
    id: "salbutamol",
    genericName: "Salbutamol (Albuterol)",
    brands: [
      "Ventolin",
      "Asmalin",
      "Pulmax",
      "RiteMED Salbutamol",
      "Airsal",
    ],
    commonForms: [
      "Inhaler (MDI) 100 mcg/actuation",
      "Nebulizing solution 2.5 mg/2.5 mL",
      "Tablet 2 mg",
      "Syrup 2 mg/5 mL",
    ],
    defaultDose: "1 to 2 puffs or 1 nebule",
    defaultFrequency: "every 4 to 6 hours as needed for bronchospasm",
    defaultDuration: "5 days",
    defaultQuantity: "1 canister / 6 nebules",
    defaultInstructions: "Inhale as directed. Rinse mouth with water after use.",
    indication: "Bronchospasm, bronchial asthma, and wheezing",
    therapeuticClass: "Short-Acting Beta-2 Agonist (SABA)",
    productInfo: {
      description: "Quick-acting bronchodilator for prompt relief of bronchospasm in asthma and COPD.",
      dosageAdvice: "1 to 2 inhalations every 4 to 6 hours as needed for acute shortness of breath or wheezing.",
      cautions: "May cause transient palpitations, fine hand tremors, or tachycardia.",
    },
  },
  {
    id: "salbutamol-ipratropium",
    genericName: "Salbutamol + Ipratropium Bromide",
    brands: [
      "Combivent Respimat",
      "Duovent",
      "Pulmodual",
      "Berodual (+Fenoterol)",
    ],
    commonForms: [
      "Respimat Inhaler 20 mcg/100 mcg",
      "Unit-dose Nebule 2.5 mL",
    ],
    defaultDose: "1 nebule via nebulizer or 1 puff",
    defaultFrequency: "every 6 to 8 hours as needed",
    defaultDuration: "5 days",
    defaultQuantity: "6 nebules",
    defaultInstructions: "Nebulize over 10 to 15 minutes. Rinse mouth after use.",
    indication: "Acute bronchospasm in asthma and COPD",
    therapeuticClass: "Bronchodilator (SABA + SAMA)",
    productInfo: {
      description: "Synergistic dual bronchodilator combining beta-2 adrenergic stimulation and muscarinic receptor blockade.",
      dosageAdvice: "1 unit-dose nebule nebulized every 6 to 8 hours as needed.",
      cautions: "Protect eyes from nebulizer mist. Caution in prostatic hypertrophy or glaucoma.",
    },
  },
  {
    id: "amlodipine",
    genericName: "Amlodipine Besilate",
    brands: [
      "Norvasc",
      "Amlife",
      "RiteMED Amlodipine",
      "Amvaz",
      "Cardiovasc",
    ],
    commonForms: [
      "Tablet 5 mg",
      "Tablet 10 mg",
    ],
    defaultDose: "1 Tablet",
    defaultFrequency: "once a day",
    defaultDuration: "30 days",
    defaultQuantity: "30",
    defaultInstructions: "Take once daily in the morning, with or without food",
    indication: "Essential hypertension and chronic stable angina",
    therapeuticClass: "Calcium Channel Blocker (Dihydropyridine)",
    productInfo: {
      description: "Long-acting calcium channel blocker that relaxes arterial vascular smooth muscle to reduce blood pressure.",
      dosageAdvice: "Initial 5 mg once daily, may be increased to 10 mg once daily after 1 to 2 weeks.",
      cautions: "Watch for peripheral ankle edema or flushing.",
    },
  },
  {
    id: "losartan",
    genericName: "Losartan Potassium",
    brands: [
      "Cozaar",
      "Arbloc",
      "Lifezar",
      "RiteMED Losartan",
      "Losar",
      "K-Zaar",
    ],
    commonForms: [
      "Film-coated tablet 50 mg",
      "Film-coated tablet 100 mg",
    ],
    defaultDose: "1 Tablet",
    defaultFrequency: "once a day",
    defaultDuration: "30 days",
    defaultQuantity: "30",
    defaultInstructions: "Take once daily at the same time each day",
    indication: "Hypertension and renal protection in type 2 diabetic nephropathy",
    therapeuticClass: "Angiotensin II Receptor Blocker (ARB)",
    productInfo: {
      description: "First-line ARB that blocks vasoconstriction and aldosterone secretion without causing dry cough.",
      dosageAdvice: "50 mg once daily, increased to 100 mg once daily if required.",
      cautions: "Contraindicated in pregnancy. Monitor serum potassium and creatinine.",
    },
  },
  {
    id: "metformin",
    genericName: "Metformin Hydrochloride",
    brands: [
      "Glucophage",
      "Formin",
      "RiteMED Metformin",
      "Glumet",
      "Diaformin",
    ],
    commonForms: [
      "Tablet 500 mg",
      "Extended-release tablet 500 mg",
      "Extended-release tablet 850 mg",
      "Extended-release tablet 1000 mg",
    ],
    defaultDose: "1 Tablet",
    defaultFrequency: "twice a day with meals",
    defaultDuration: "30 days",
    defaultQuantity: "60",
    defaultInstructions: "Take with or immediately after meals to reduce stomach discomfort",
    indication: "Type 2 Diabetes Mellitus",
    therapeuticClass: "Biguanide Antidiabetic",
    productInfo: {
      description: "First-line oral antidiabetic that decreases hepatic glucose production and enhances insulin sensitivity.",
      dosageAdvice: "500 mg 1 to 2 times daily with meals, titrating gradually.",
      cautions: "Take with food to minimize GI upset. Contraindicated in severe renal impairment (eGFR < 30).",
    },
  },
  {
    id: "rosuvastatin",
    genericName: "Rosuvastatin Calcium",
    brands: [
      "Crestor",
      "Rosuvas",
      "RiteMED Rosuvastatin",
      "Rosuvin",
      "Lipitor-R",
    ],
    commonForms: [
      "Film-coated tablet 10 mg",
      "Film-coated tablet 20 mg",
    ],
    defaultDose: "1 Tablet",
    defaultFrequency: "once a day at bedtime",
    defaultDuration: "30 days",
    defaultQuantity: "30",
    defaultInstructions: "Take once daily at bedtime with or without food",
    indication: "Hypercholesterolemia, dyslipidemia, and cardiovascular risk reduction",
    therapeuticClass: "HMG-CoA Reductase Inhibitor (Statin)",
    productInfo: {
      description: "High-intensity statin for lowering LDL cholesterol and triglycerides while raising HDL.",
      dosageAdvice: "10 mg to 20 mg once daily at bedtime.",
      cautions: "Report unexplained muscle pain, tenderness, or weakness immediately.",
    },
  },
  {
    id: "carbocisteine",
    genericName: "Carbocisteine",
    brands: [
      "Solmux",
      "Loviscol",
      "RiteMED Carbocisteine",
      "Mucolite",
    ],
    commonForms: [
      "Capsule 500 mg",
      "Syrup 250 mg/5 mL",
      "Oral Drops 50 mg/mL",
    ],
    defaultDose: "1 Capsule",
    defaultFrequency: "3 times a day",
    defaultDuration: "5 days",
    defaultQuantity: "15",
    defaultInstructions: "Drink plenty of water throughout the day",
    indication: "Productive cough with excessive, thick mucus / phlegm",
    therapeuticClass: "Mucolytic",
    productInfo: {
      description: "Normalizes mucus viscosity, reducing sputum thickness to make phlegm easier to expectorate.",
      dosageAdvice: "Adults: 500 mg 3 times daily with plenty of fluids.",
      cautions: "Caution in patients with active peptic ulcer.",
    },
  },
  {
    id: "betahistine",
    genericName: "Betahistine Dihydrochloride",
    brands: [
      "Serc",
      "Betaserc",
      "Exigo",
      "RiteMED Betahistine",
    ],
    commonForms: [
      "Tablet 16 mg",
      "Tablet 24 mg",
    ],
    defaultDose: "1 Tablet",
    defaultFrequency: "twice a day (every 12 hours)",
    defaultDuration: "14 days",
    defaultQuantity: "28",
    defaultInstructions: "Take with or after meals",
    indication: "Vertigo, dizziness, tinnitus, and Meniere's disease",
    therapeuticClass: "Histamine Analogue / Antivertigo",
    productInfo: {
      description: "Improves microcirculation in the inner ear to alleviate vertigo, tinnitus, and hearing loss.",
      dosageAdvice: "16 mg to 24 mg twice daily with food.",
      cautions: "Caution in patients with bronchial asthma or peptic ulcer disease.",
    },
  },
  {
    id: "tranexamic-acid",
    genericName: "Tranexamic Acid",
    brands: [
      "Hemostan",
      "Tranex",
      "RiteMED Tranexamic Acid",
      "Placid",
    ],
    commonForms: [
      "Capsule 500 mg",
    ],
    defaultDose: "1 Capsule",
    defaultFrequency: "3 times a day",
    defaultDuration: "3 to 5 days",
    defaultQuantity: "9",
    defaultInstructions: "Take with a full glass of water. Do not exceed prescribed duration.",
    indication: "Menorrhagia (heavy menstrual bleeding) and acute hemorrhage",
    therapeuticClass: "Antifibrinolytic Hemostatic Agent",
    productInfo: {
      description: "Competitively inhibits plasminogen activation to stabilize fibrin clots and reduce bleeding.",
      dosageAdvice: "500 mg 3 times daily during active heavy bleeding for up to 4 days.",
      cautions: "Contraindicated in active thromboembolic disease or history of venous thrombosis.",
    },
  },
];

export const CLINIC_PRESCRIPTION_TEMPLATES = [
  {
    name: "Allergic Rhinitis Standard Protocol",
    category: "Allergy & Respiratory",
    items: [
      {
        genericName: "Montelukast + Levocetirizine",
        brand: "Allerkast",
        strengthForm: "Film-coated tablet 10 mg/5 mg",
        dose: "1 Film-coated tablet",
        frequency: "once a day",
        duration: "5 days",
        quantity: "5",
        instructions: "Take before bedtime",
        indication: "Allergic rhinitis",
      },
    ],
    notes: "Avoid known allergens, dust, and smoke. Keep room well-ventilated.",
  },
  {
    name: "Cough & Cold / URTI Relief Protocol",
    category: "Upper Respiratory",
    items: [
      {
        genericName: "Dextromethorphan + Phenylpropanolamine + Paracetamol",
        brand: "Tuseran Forte",
        strengthForm: "Capsule 15 mg/25 mg/325 mg",
        dose: "1 Capsule",
        frequency: "3 times a day",
        duration: "5 days",
        quantity: "15",
        instructions: "Take with or without food",
        indication: "Cough, cold, and fever",
      },
    ],
    notes: "Increase oral fluid intake (at least 2 to 3 liters of water/day). Get adequate rest.",
  },
  {
    name: "Acute Bronchitis / Bacterial Infection",
    category: "Antibiotics",
    items: [
      {
        genericName: "Azithromycin",
        brand: "Azithro-Natrapharm",
        strengthForm: "Film-coated tablet 500 mg",
        dose: "1 Film-coated tablet",
        frequency: "once a day",
        duration: "5 days",
        quantity: "5",
        instructions: "Take with or without food",
        indication: "Bacterial respiratory tract infection",
      },
      {
        genericName: "Paracetamol",
        brand: "Biogesic",
        strengthForm: "Tablet 500 mg",
        dose: "1 Tablet",
        frequency: "every 4 to 6 hours as needed",
        duration: "3 days",
        quantity: "10",
        instructions: "Take for fever or body aches",
        indication: "Fever and body aches",
      },
    ],
    notes: "Complete the 5-day antibiotic course even if feeling better.",
  },
  {
    name: "Acute Gastroenteritis (Hydration + Antiemetic)",
    category: "Gastrointestinal",
    items: [
      {
        genericName: "Oral Rehydration Salts (ORS)",
        brand: "Hydrite",
        strengthForm: "Powder sachet for 200 mL solution",
        dose: "1 sachet dissolved in 200 mL drinking water",
        frequency: "after each loose bowel movement",
        duration: "3 days",
        quantity: "6",
        instructions: "Sip slowly after each loose stool. Discard unused reconstituted solution after 24 hours.",
        indication: "Dehydration from acute gastroenteritis",
      },
      {
        genericName: "Domperidone",
        brand: "Motilium",
        strengthForm: "Film-coated tablet 10 mg",
        dose: "1 Tablet",
        frequency: "3 times a day",
        duration: "3 days",
        quantity: "9",
        instructions: "Take 15 to 30 minutes before meals for nausea",
        indication: "Nausea and vomiting",
      },
    ],
    notes: "Eat bland soft foods (BRAT diet: bananas, rice, applesauce, toast). Avoid oily or dairy foods.",
  },
  {
    name: "Dyspepsia / Acid Reflux (GERD)",
    category: "Gastrointestinal",
    items: [
      {
        genericName: "Omeprazole",
        brand: "Losec",
        strengthForm: "Capsule 20 mg",
        dose: "1 Capsule",
        frequency: "once a day",
        duration: "14 days",
        quantity: "14",
        instructions: "Take 30 minutes before breakfast on an empty stomach",
        indication: "GERD / Hyperacidity",
      },
      {
        genericName: "Aluminum Hydroxide + Magnesium Hydroxide + Simethicone",
        brand: "Kremil-S Advance",
        strengthForm: "Chewable tablet",
        dose: "1 to 2 Chewable tablets",
        frequency: "3 times a day as needed",
        duration: "5 days",
        quantity: "10",
        instructions: "Chew thoroughly 1 hour after meals and at bedtime",
        indication: "Heartburn and gas",
      },
    ],
    notes: "Avoid lying down for 2 hours after meals. Avoid spicy, citrus, coffee, and acidic foods.",
  },
];

export const PPD_PRESCRIPTION_TEMPLATES = CLINIC_PRESCRIPTION_TEMPLATES;
export const FORMULARY_MEDICINES = PPD_MEDICINES;

export function createEmptyPrescriptionItem(): PrescriptionItemDraft {
  return {
    id: Math.random().toString(36).slice(2, 9),
    genericName: "",
    brand: "",
    strengthForm: "",
    dose: "1 Tablet",
    frequency: "once a day",
    duration: "5 days",
    quantity: "5",
    instructions: "",
    indication: "",
  };
}
